### ISSUE TITLE
For modified version of Swinject?

### ISSUE THREAD

**Issue by gcutrini** [Nikita2k/SwiftViper#1]
Hi Nikita2k, the templated assembly uses a initialiser not defined in Swinject 1.0.0

`assembler = try! Assembler(assemblies: [TestContainer()], parentAssembler: parentAssembler)`

Are these for a custom Swinject?
Many thanks!

**Comment by yoichitgy** [comment]
Hi @gcutrini, I still didn't release a version including the feature.

I wanted to add some other features too, but I will release Swinject 1.1.0 with only the new Assembler feature shortly.

**Comment by gcutrini** [comment]
Thanks for the clarification and for Swinject @yoichitgy !

**Comment by Nikita2k** [comment]
@gcutrini Yes, @yoichitgy is right. So you can add to your podfile `pod 'Swinject', :git => 'https://github.com/Swinject/Swinject.git', :commit => '48a8504'` and wait for new version.

@yoichitgy Thank you for explanation! I another small fix to do, that is good to see in a version with assembler hierarchy, hope to do it today

**Comment by yoichitgy** [comment]
@Nikita2k did you mean you were going to send PR to Swinject for the small fix? If so, I'll wait to release v1.1.0 of Swinject. If not, I'll release it in this week.
